###################################################
# Services
###################################################
services:

  ###################################################
  # Service: backend
  ###################################################
  backend:
    ports:
      - 8182:8188
    image: pytorch/pytorch
    build:
      context: ./
      target: backend-dev
    environment:
      DUMMY: true
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /usr/local/app/src
        - path: ./backend/package.json
          action: rebuild
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`)
      traefik.http.services.backend.loadbalancer.server.port: 8188
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
