###################################################
# Services
###################################################
services:

  ###################################################
  # Service: proxy
  #
  # We expose port 80 to connect to the proxy from the host machine.
  ###################################################
  proxy:
    image: traefik:v2.11
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ###################################################
  # Service: backend
  # 
  # This service is the Node.js server that provides the API for the app.
  # When the container starts, it will use the image that results
  # from building the Dockerfile, targeting the backend-dev stage.
  #
  # The Compose Watch configuration is used to automatically sync the code
  # from the host machine to the container. This allows the server to be
  # automatically reloaded when code changes are made.
  #
  # The environment variables configure the application to connect to the
  # database, which is also configured in this Compose file. We obviously
  # wouldn't hard-code these values in a production environment. But, in
  # dev, these values are fine.
  #
  # Finally, the labels are used to configure Traefik (the reverse proxy) with
  # the appropriate routing rules. In this case, all requests to localhost/api/*
  # will be forwarded to this service's port 3000. 
  ###################################################
  backend:
    build:
      context: ./
      target: backend-dev
    environment:
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /usr/local/app/src
        - path: ./backend/package.json
          action: rebuild
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 3000

  ###################################################
  # Service: client
  #
  # The client service is the React app that provides the frontend for the app.
  # When the container starts, it will use the image that results from building
  # the Dockerfile, targeting the dev stage.
  #
  # The Compose Watch configuration is used to automatically sync the code from
  # the host machine to the container. This allows the client to be automatically
  # reloaded when code changes are made.
  # 
  # The labels are used to configure Traefik (the reverse proxy) with the 
  # appropriate routing rules. In this case, all requests to localhost will be
  # forwarded to this service's port 5173.
  ###################################################
  client:
    build:
      context: ./
      target: client-dev
    develop:
      watch:
        - path: ./client/src
          action: sync
          target: /usr/local/app/src
        - path: ./client/package.json
          action: rebuild
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 5173
