###################################################
# Services
###################################################
services:

  ###################################################
  # Service: proxy
  #
  # We expose port 80 to connect to the proxy from the host machine.
  ###################################################
  proxy:
    image: traefik:v2.11
    command: --providers.docker
    ports:
      - 8188:8188
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ###################################################
  # Service: backend
  ###################################################
  backend:
    image: pytorch/pytorch
    build:
      context: ./
      target: backend-dev
    environment:
      DUMMY: true
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /usr/local/app/src
        - path: ./backend/package.json
          action: rebuild
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`)
      traefik.http.services.backend.loadbalancer.server.port: 8188
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
